// Auto-generated.
#include "modules.h"

#include "cons.h"
#include "value.h"

#include "strings.h"

oop modules_decls() { return LIST(LIST(make_symbol("defmacro"), make_symbol("make-module"), LIST(make_symbol("&rest"), make_symbol("symbols")), LIST(make_symbol("with-gensyms"), LIST(make_symbol("result")), LIST(make_symbol("quasiquote"), LIST(make_symbol("let"), LIST(LIST(LIST(make_symbol("unquote"), make_symbol("result")), LIST(make_symbol("make-dict")))), LIST(make_symbol("unquote-splicing"), LIST(make_symbol("map"), LIST(make_symbol("lambda"), LIST(make_symbol("sym")), LIST(make_symbol("with-asserts"), LIST(LIST(make_symbol("symbol?"), make_symbol("sym"))), LIST(make_symbol("quasiquote"), LIST(make_symbol("dict-put!"), LIST(make_symbol("unquote"), make_symbol("result")), LIST(make_symbol("quote"), LIST(make_symbol("unquote"), make_symbol("sym"))), LIST(make_symbol("unquote"), make_symbol("sym")))))), make_symbol("symbols"))), LIST(make_symbol("unquote"), make_symbol("result")))))), LIST(make_symbol("defn"), make_symbol("expand-module-clauses"), LIST(make_symbol("module-clauses")), LIST(make_symbol("defn"), make_symbol("normalize-var-clause"), LIST(make_symbol("var")), LIST(make_symbol("cond"), LIST(LIST(make_symbol("symbol?"), make_symbol("var")), LIST(make_symbol("list"), make_symbol("var"), make_symbol("var"))), LIST(LIST(make_symbol("list?"), make_symbol("var")), LIST(make_symbol("list"), LIST(make_symbol("first"), make_symbol("var")), LIST(make_symbol("second"), make_symbol("var")))), LIST(make_symbol("true"), LIST(make_symbol("error"), make_string("Unsupported module import clause "), make_symbol("var"))))), LIST(make_symbol("defn"), make_symbol("expand-module-clause"), LIST(LIST(make_symbol("module-name"), make_symbol("&rest"), make_symbol("vars"))), LIST(make_symbol("map"), LIST(make_symbol("lambda"), LIST(LIST(make_symbol("new-var-name"), make_symbol("old-var-name"))), LIST(make_symbol("quasiquote"), LIST(LIST(make_symbol("unquote"), make_symbol("new-var-name")), LIST(make_symbol("dict-get"), LIST(make_symbol("unquote"), make_symbol("module-name")), LIST(make_symbol("quote"), LIST(make_symbol("unquote"), make_symbol("old-var-name"))))))), LIST(make_symbol("map"), make_symbol("normalize-var-clause"), make_symbol("vars")))), LIST(make_symbol("apply"), make_symbol("append"), LIST(make_symbol("map"), make_symbol("expand-module-clause"), make_symbol("module-clauses")))), LIST(make_symbol("defmacro"), make_symbol("import"), LIST(make_symbol("module-clauses"), make_symbol("&rest"), make_symbol("body")), LIST(make_symbol("quasiquote"), LIST(make_symbol("let"), LIST(make_symbol("unquote"), LIST(make_symbol("expand-module-clauses"), make_symbol("module-clauses"))), LIST(make_symbol("unquote-splicing"), make_symbol("body")))))); }

