# -*- mode:python -*-

filegroup(
  name = "translate_scm",
  srcs = ["translate.scm"],
  visibility = ["//visibility:public"],
)

filegroup(
  name = "run_tests_fn",
  srcs = ["run-tests.fn"],
  visibility = ["//visibility:public"],
)

filegroup(
  name = "run_tests_sh",
  srcs = ["run_tests.sh"],
  visibility = ["//visibility:public"],
)
